# Generated by Django 5.0.2 on 2024-02-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_alter_reply_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={},
        ),
        migrations.AlterModelManagers(
            name='reply',
            managers=[
            ],
        ),
    ]
